### ISSUE TITLE
Specified string is not recognized

### ISSUE THREAD

**Issue by triska** [mb64/prolog#2]
Currently, I get:

<pre>
<b>&gt; "abc" = [X|_]</b> ?
...
  = Expected one of ... <b>string</b>
</pre>

Expected answer: `X = a`, on the grounds that "string" colloquially means a **list of characters**, and I am specifying such a list using the double quoted term `"abc"`.

**Comment by mb64** [comment]
Yep, that's an issue!  Thanks for pointing it out.

In general, I see this project kind of like [this 1668 illustration of a shark](https://saveourseas.com/wp-content/uploads/2016/07/Blog20160711Im02.jpg): well-intentioned and detailed, but dang, had that guy ever actually *seen* a shark?

Similarly, when I implemented "strings", I didn't know how strings worked in Prolog -- I just wanted to be able to print stuff out.  Here's what there is currently, and what I think I should change it to -- please correct me if I'm wrong about any of this:

 * `hi` is called a functor by the lexer.  I think it's just an atom, not a functor, but tbh I'm not entirely sure the difference between an atom and a zero-argument functor.
 * `'hi'` is called a string by the lexer.  It is distinct from an atom, and just represents some opaque bit of data.  This should change to be identical to `hi`.
 * `"hi"` is not parsed.  It should be, as you say, a list of characters.

And just to confirm, is a "character" the same as a single-character functor? Like `"abc" = [a,b,c]`?

**Comment by triska** [comment]
Yes `hi` is an atom. A *functor* is a functor name together with an arity. So for example, in the term `f(a,b,c)`, the principal functor is&nbsp;`f/3`.  We also have the following connection:

<pre>
3.134 principal functor: The principal functor of a
compound term is F/N if the functor of the compound
term is F and its arity is N.

The principal functor of an atomic term is C/0 if the
atomic term is C.
</pre>


Therefore, we have for example:

<pre>
<b>?- functor(a, F, A).</b>
   F = a, A = 0.
</pre>

Single quotes can be used to denote atoms, if necessary, for example if the atoms contains spaces, double quotes etc.

Yes, I am using "character" synonymously with "one-char atom", i.e., atom of length&nbsp;1:

<pre>
<b>7.1.4.1 Characters and one-char atoms</b>

C, a set of characters, is an implementation defined subset
of PCS, the processor character set (6.5),

Any member of C is represented in a Prolog term by a
one-char atom whose name is that member of C.

NOTE - There is a one-to-one mapping between members of
C (characters) and members of CC (character codes) (7.1.2.2).
</pre>

**Comment by mb64** [comment]
This should be fixed now:
```
> 'hello' = hello ?

Yes.
> "abc" = [X | Tail] ?

Solution:
   Tail = [b, c]
   X = a
```
